#!/bin/bash

export EDITOR=vim
export BROWSER=firefox
export TERM='xterm-256color'
export NO_AT_BRIDGE=1

# Base16 Shell
#BASE16_SHELL="$HOME/.config/base16-shell/base16-utk.dark.sh"
BASE16_SHELL="$HOME/.config/base16-shell/base16-felt.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

#Define some colors:
# Reset
no_color='\e[0m'     # text reset
# Regular colors:
blk='\e[0;30m'  # black
red='\e[0;31m'  # red
grn='\e[0;32m'  # green
ylw='\e[0;33m'  # yellow
blu='\e[0;34m'  # blue
ppl='\e[0;35m'  # purple
cyn='\e[0;36m'  # cyan
wht='\e[0;37m'  # white
# Bold colors:
bld_blk='\e[1;30m'  # black
bld_red='\e[1;31m'  # red
bld_grn='\e[1;32m'  # green
bld_ylw='\e[1;33m'  # yellow
bld_blu='\e[1;34m'  # blue
bld_ppl='\e[1;35m'  # purple
bld_cyn='\e[1;36m'  # cyan
bld_wht='\e[1;37m'  # white
# Underline:
uln_blk='\e[4;30m'  # black
uln_red='\e[4;31m'  # red
uln_grn='\e[4;32m'  # green
uln_ylw='\e[4;33m'  # yellow
uln_blu='\e[4;34m'  # blue
uln_ppl='\e[4;35m'  # purple
uln_cyn='\e[4;36m'  # cyan
uln_wht='\e[4;37m'  # white
# Background
on_blk='\e[40m'    # black
on_red='\e[41m'    # red
on_grn='\e[42m'    # green
on_ylw='\e[43m'    # yellow
on_blu='\e[44m'    # blue
on_ppl='\e[45m'    # purple
on_cyn='\e[46m'    # cyan
on_wht='\e[47m'    # white
# High intensity
hi_blk='\e[0;90m'  # black
hi_red='\e[0;91m'  # red
hi_grn='\e[0;92m'  # green
hi_ylw='\e[0;93m'  # yellow
hi_blu='\e[0;94m'  # blue
hi_ppl='\e[0;95m'  # purple
hi_cyn='\e[0;96m'  # cyan
hi_wht='\e[0;97m'  # white
# Bold high intensity
hi_bld_blk='\e[1;90m'  # black
hi_bld_red='\e[1;91m'  # red
hi_bld_grn='\e[1;92m'  # green
hi_bld_ylw='\e[1;93m'  # yellow
hi_bld_blu='\e[1;94m'  # blue
hi_bld_ppl='\e[1;95m'  # purple
hi_bld_cyn='\e[1;96m'  # cyan
hi_bld_wht='\e[1;97m'  # white
# High intensity on background
hi_bld_on_blk='\e[0;100m'  # black
hi_bld_on_red='\e[0;101m'  # red
hi_bld_on_grn='\e[0;102m'  # green
hi_bld_on_ylw='\e[0;103m'  # yellow
hi_bld_on_blu='\e[0;104m'  # blue
hi_bld_on_ppl='\e[0;105m'  # purple
hi_bld_on_cyn='\e[0;106m'  # cyan
hi_bld_on_wht='\e[0;107m'  # white

bld_rng='\033[38;5;16;48;1;21m'
rng='\033[38;5;16;48;1;21m'
#Change Prompt-- basic prompt
#the following two lines mean the same thing just with different syntax:
#export PS1='\[\033[01;32m\]\u\[\033[01;34m\]::\[\033[01;31m\]\h \[\033[00;34m\]{ \[\033[01;34m\]\w \[\033[00;34m\]}\[\033[01;32m\]-> \[\033[00m\]'
#export PS1="$bld_grn\u$bld_blu::$bld_red\h $bld_blu{ \w }$bld_grn->$no_color"
#export PS1="\[$bld_ppl\]┌─[\[$bld_ylw\]\t \[$bld_grn\]\u\[$bld_blu\]::\[$bld_red\]\h\[$bld_blu\] \w\[$bld_ppl\]] \n\[$bld_ppl\]└─>\[$no_color\]"
#export PS1="\[$bld_ppl\]┌─[\[$bld_wht\]\t \[$bld_cyn\]\u\[$bld_wht\]::\[$bld_rng\]\h\[$bld_blu\] \w\[$bld_ppl\]] \n\[$bld_ppl\]└─>\[$no_color\]"
#export PS1="\[$bld_ppl\]┌─[\[$bld_cyn\]\u\[$bld_wht\]::\[$bld_rng\]\h\[$bld_blu\] \w\[$bld_ppl\]] \n\[$bld_ppl\]└─>\[$no_color\]"
#export PS1="\[$bld_ppl\]┣━\[$bld_cyn\]\u\[$bld_wht\]:\[$bld_rng\]\h\[$bld_blu\]\w\[$bld_ppl\]┃ \n\[$bld_ppl\]┣━\[$no_color\]"
export PS1="\[$ppl\]<\[$wht\]\t•\[$cyn\]\u\[$wht\]•\[$rng\]\h\[$blu\] \w\[$ppl\]> \n\[$ppl\]>\[$no_color\]"

PROMPT_DIRTRIM=4 

set -o vi

bind -m vi-insert "\C-l":clear-screen
