#!/bin/sh
weather(){
URL='http://www.accuweather.com/en/us/knoxville-tn/37922/weather-forecast/331087'

wget -q -O- "$URL" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $2": "$16", "$12"°" }'| head -1
}
